export const RACE_EXPIRY_BUFFER_SECONDS = 60
export const COUNTDOWN_INTERVAL_MS = 1000
export const RACE_REFRESH_INTERVAL_MS = 30000
export const REFILL_RETRY_WINDOW_MS = 5000
export const VISIBLE_RACE_COUNT = 5
